// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: dataprocessor.proto

package hubapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DataProcessor_ProcessData_FullMethodName = "/hubapiv1.DataProcessor/ProcessData"
)

// DataProcessorClient is the client API for DataProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataProcessorClient interface {
	ProcessData(ctx context.Context, in *PubSubGenericMessage, opts ...grpc.CallOption) (*PublicPost, error)
}

type dataProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProcessorClient(cc grpc.ClientConnInterface) DataProcessorClient {
	return &dataProcessorClient{cc}
}

func (c *dataProcessorClient) ProcessData(ctx context.Context, in *PubSubGenericMessage, opts ...grpc.CallOption) (*PublicPost, error) {
	out := new(PublicPost)
	err := c.cc.Invoke(ctx, DataProcessor_ProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProcessorServer is the server API for DataProcessor service.
// All implementations must embed UnimplementedDataProcessorServer
// for forward compatibility
type DataProcessorServer interface {
	ProcessData(context.Context, *PubSubGenericMessage) (*PublicPost, error)
	mustEmbedUnimplementedDataProcessorServer()
}

// UnimplementedDataProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedDataProcessorServer struct {
}

func (UnimplementedDataProcessorServer) ProcessData(context.Context, *PubSubGenericMessage) (*PublicPost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessData not implemented")
}
func (UnimplementedDataProcessorServer) mustEmbedUnimplementedDataProcessorServer() {}

// UnsafeDataProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProcessorServer will
// result in compilation errors.
type UnsafeDataProcessorServer interface {
	mustEmbedUnimplementedDataProcessorServer()
}

func RegisterDataProcessorServer(s grpc.ServiceRegistrar, srv DataProcessorServer) {
	s.RegisterService(&DataProcessor_ServiceDesc, srv)
}

func _DataProcessor_ProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubSubGenericMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessorServer).ProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataProcessor_ProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessorServer).ProcessData(ctx, req.(*PubSubGenericMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// DataProcessor_ServiceDesc is the grpc.ServiceDesc for DataProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hubapiv1.DataProcessor",
	HandlerType: (*DataProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessData",
			Handler:    _DataProcessor_ProcessData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataprocessor.proto",
}
